### ISSUE TITLE
`closePortal` prop causes React 15.2.0 warning

### ISSUE THREAD

**Issue by STRML** [tajo/react-portal#80]
```
warning.js:44 Warning: Unknown prop `closePortal` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by Tooltip)
```

A thought - could check if `component.type === 'string'` and only pass the prop along if it is not.

**Comment by tajo** [comment]
Thanks! I did something similar https://github.com/tajo/react-portal/blob/master/lib/portal.js#L156

The fix released as `v2.2.1`.

**Comment by kibs** [comment]
I still get this error on latest react, 15.3.1 and portal 2.2.1.. only it says "div" tag, having some trouble figuring out why it appears.

**Comment by kibs** [comment]
nevermind, i found the problem

**Comment by rbliss** [comment]
@kibs I'm getting this as well. What was your fix?

**Comment by austinbourdier** [comment]
@kibs - what was the problem/solution you found?

**Comment by scottjason** [comment]
@kibs fix ?

**Comment by kibs** [comment]
Sorry :) It is so long ago, i don't really remember it. I think the problem was with my own code, and not related to this library. I think the fix, but not sure, was to have the first child to <Portal> a component which allowed the closePortal prop, and inside that, have a div as first element, so not a div directly as child to portal

**Comment by kibs** [comment]
so

```
<Portal>
    <MyComp />
</Portal>
```
instead of

```
<Portal>
    <div />
</Portal>
```
